spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: /auth/
  datasource:
    url: jdbc:h2:file:./h2/formeditor
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
